refactoring, removed abs dependency, added pacaur dependency, added pbget dependency

diff --git a/srcpac b/srcpac
--- a/srcpac
+++ b/srcpac
@@ -31,7 +31,6 @@ source_file() {
   [ -f "${1}" ] && source "${1}"
 }
 
-source_file "/etc/abs.conf"
 source_file "/etc/makepkg.conf"
 source_file "~/.makepkg.conf"
 source_file "/etc/srcpac.conf"
@@ -83,7 +82,7 @@ version()
 ##ost
 apply_config()
 {
-  conf=/etc/srcpac.d/${1}
+  conf=~/.config/srcpac.d/${1}
   if [ -f ${conf} ]; then
     if [ "${3}" = "noreplace" ]; then
       sed -f ${conf} ${2}/PKGBUILD | ${PAGER}
@@ -94,7 +93,7 @@ apply_config()
 }
 
 is_installed() {
-  $PACMAN -Q $1 &> /dev/null
+  pacaur -Q $1 &> /dev/null
   return $?
 }
 
@@ -107,56 +106,31 @@ get_candidates()
   local found=0
   is_target=$2
 
-  for pkgbuild in `find ${ABSROOT} -name PKGBUILD`; do
-    unset pkgbase
-    unset pkgname
-    source "$pkgbuild" &> /dev/null
-    if [ "${1}" = "${pkgbase}" ]; then
-      found=1
-      break
-    else
-      for _pkgname in "${pkgname[@]}"; do
-        if [ "${1}" = "${_pkgname}" ]; then
-          found=1
-          break
-        fi
-      done
-    fi
+  # Backup target's makedepends array
+  local _makedepends=${makedepends[@]}
 
-    if [ ${found} -eq 1 ]; then
-      if [ $is_target -eq 1 ]; then
-        # Backup target's makedepends array
-       local _makedepends=${makedepends[@]}
+  if [ ${BUILDDEPS} -eq 1 ]; then
+    for _dep in ${depends[@]}; do
+      is_installed ${_dep%%[<>=]*}
+      installed=$?
+      [ "${installed}" -eq 0 ] && continue
+      [ "${installed}" -eq 0 ] && continue
 
-        if [ ${BUILDDEPS} -eq 1 ]; then
-          for _dep in ${depends[@]}; do
-            is_installed ${_dep%%[<>=]*}
-            installed=$?
-            [ "${installed}" -eq 0 ] && continue
-
-            get_candidates ${_dep%%[<>=]*} 0
-          done
-        fi
-        if [ ${BUILDMAKEDEPS} -eq 1 ]; then
-          for _makedep in ${_makedepends[@]}; do
-            is_installed ${_makedep%%[<>=]*}
-            installed=$?
-            [ "${installed}" -eq 0 ] && continue
-
-            get_candidates ${_makedep%%[<>=]*} 0
-          done
-        fi
-      fi
-      break
-    fi
-  done
-
-  if [ ${found} -eq 1 ]; then
-    candidate="${pkgbuild##${ABSROOT}}"
-    candidates[${#candidates[@]}]="${candidate%%/PKGBUILD}"
-  else
-    printf "$(gettext "Error: Could not find %s under %s")\n" "${1}" "${ABSROOT}"
+      get_candidates ${_dep%%[<>=]*} 0
+    done
   fi
+  if [ ${BUILDMAKEDEPS} -eq 1 ]; then
+    for _makedep in ${_makedepends[@]}; do
+      is_installed ${_makedep%%[<>=]*}
+      installed=$?
+      [ "${installed}" -eq 0 ] && continue
+
+      get_candidates ${_makedep%%[<>=]*} 0
+    done
+  fi
+
+  candidate="${1}"
+  candidates[${#candidates[@]}]="${candidate}"
 }
 
 ##
@@ -167,7 +141,7 @@ refresh()
   printf "$(gettext "Starting ABS sync...")"
   abs &> /dev/null
   printf "$(gettext "done")\n"
-  $PACMAN -Sy
+  pacaur -Sy
   if [ ${#args[@]} -eq 0 -a $SYSUPGRADE -eq 0 ]; then
     exit 0
   fi
@@ -206,8 +180,7 @@ build_package() {
   shift
 
   local pkg=${1##*/}
-  local pkgdir="${ABSROOT}/${1}"
-  local builddir="/var/srcpac/${pkg}"
+  local builddir="~/.cache/srcpac"
 
   local succeed=0
 
@@ -216,17 +189,15 @@ build_package() {
   [ $MAKEDEPS -eq 1 ] && MAKEPKGOPTS="${MAKEPKGOPTS} -r"
   [ $NOCONFIRM -eq 1 ] && MAKEPKGOPTS="${MAKEPKGOPTS} --noconfirm"
 
-  local SPLITPKG=0
-  [ "${pkg}" != "${pkgdir##*/}" ] && SPLITPKG=1
-  [ $SPLITPKG -eq 1 ] && MAKEPKGOPTS="${MAKEPKGOPTS} --pkg ${pkg}"
-
   # create the build dir and apply configuration
-  [[ -d ${builddir} ]] && rm -rf ${builddir}
-  mkdir -p ${builddir}
-  cp ${pkgdir}/* ${builddir}
-  apply_config ${pkg} ${builddir}
+  [[ ! -d ${builddir} ]] && mkdir ${builddir}
+  [[ -d ${builddir}/${pkg} ]] && rm -rf ${builddir}/${pkg}
+  pushd ${builddir} 
+  pbget --aur ${pkg}
+  popd
+  apply_config ${pkg} ${builddir}/${pkg}
 
-  pushd ${builddir} &> /dev/null
+  pushd ${builddir}/${pkg} &> /dev/null
 
   unset epoch
   unset pkgver
@@ -234,15 +205,9 @@ build_package() {
   unset arch
   source PKGBUILD &> /dev/null
 
-  if [ -z "${SUDO_USER}" ]; then
-    chown -R nobody ${builddir}
-    makepkg ${MAKEPKGOPTS} --asroot
-    [ $? -eq 0 ] && succeed=1
-  else
-    chown -R ${SUDO_USER} ${builddir}
-    sudo -u ${SUDO_USER} makepkg ${MAKEPKGOPTS}
-    [ $? -eq 0 ] && succeed=1
-  fi
+  $EDITOR PKGBUILD
+  makepkg ${MAKEPKGOPTS}
+  [ $? -eq 0 ] && succeed=1
 
   popd &> /dev/null
 
@@ -251,8 +216,8 @@ build_package() {
   else
     local CACHEDIR=$( (grep -m 1 '^CacheDir' /etc/pacman.conf || echo 'CacheDir = /var/cache/pacman/pkg') | sed 's/CacheDir\s*=\s*//')
     local filename="${pkg}-$(get_full_version ${epoch:-0} ${pkgver} ${pkgrel})-$(get_arch ${arch}).pkg.tar.?z"
-    cp -f ${builddir}/${filename} "${CACHEDIR}"
-    rm -rf ${builddir}
+	sudo cp -f ${builddir}/${pkg}/${filename} "${CACHEDIR}"
+    rm -rf ${builddir}/${pkg}
 
     if [ "${action}" = "install" ]; then
       local PACARGS="-U"
@@ -263,8 +228,8 @@ build_package() {
       [ $ASEXPLICIT -eq 1 ] && PACARGS="${PACARGS} --asexplicit"
       [ $NOCONFIRM -eq 1 ] && PACARGS="${PACARGS} --noconfirm"
 
-      $PACMAN $PACARGS "${CACHEDIR}"/${filename}
-      [ $? -eq 0 ] && touch "/var/lib/srcpac/${pkg}"
+      pacaur $PACARGS "${CACHEDIR}"/${filename}
+      [ $? -eq 0 ] && touch ~/.config/srcpac/${pkg}
     fi
   fi
 }
@@ -423,11 +388,11 @@ check_args()
 remove()
 {
   if [ $ONLYCONF -eq 1 ]; then
-    [ -f /etc/srcpac.d/$1 ] && rm /etc/srcpac.d/$1
+    [ -f ~/.config/srcpac.d/$1 ] && rm ~/.config/srcpac.d/$1
   else
-    if [ -f /var/lib/srcpac/$1 ]; then
+    if [ -f ~/.config/srcpac/$1 ]; then
       printf "$(gettext "removing source reference %s...")" "${1}"
-      rm /var/lib/srcpac/$1
+      rm ~/.config/srcpac/$1
       printf "$(gettext "done")\n"
     fi
   fi
@@ -437,7 +402,7 @@ remove()
 # Check if a package has been built using srcpac
 ##
 is_built() {
-  ls /var/lib/srcpac/$1 &> /dev/null
+  ls ~/.config/srcpac/$1 &> /dev/null
   return $?
 }
 
@@ -450,37 +415,32 @@ main()
     exit 1
   fi
 
-  if [ ${UID} -ne 0 -a -z "${SUDO_USER}" -a ${MAJOR} != "query" ]; then
-    printf "$(gettext "Error: You need to use sudo or to be root")\n"
+  if [ ${UID} -eq 0 ]; then
+    printf "$(gettext "Error: Action cannot be performed as root")\n"
     exit 1
   fi
 
-  if [ -f /run/srcpac.lock ]; then
+  if [ -f ~/.config/srcpac.lock ]; then
     printf "$(gettext "\
 Another instance of srcpac is already running.\n\
   If you're sure srcpac is not already running\n\
-  you can remove /run/srcpac.lock")\n"
+  you can remove ~/.config/srcpac.lock")\n"
     exit 1
   fi
 
-  if [ -z "${ABSROOT}" ]; then
-    printf "$(gettext "Error: The ABSROOT environment variable is not defined")\n"
-    exit 1
-  fi
-
-  if [ ! -d /var/lib/srcpac ]; then
-    mkdir /var/lib/srcpac
+  if [ ! -d ~/.config/srcpac ]; then
+    mkdir ~/.config/srcpac
     [ $? -eq 0 ] && exit 1
   fi
 
-  if [ ! -d /etc/srcpac.d ]; then
-    mkdir /etc/srcpac.d
+  if [ ! -d ~/.config/srcpac.d ]; then
+    mkdir ~/.config/srcpac.d
     [ $? -eq 0 ] && exit 1
   fi
 
   if [ "${MAJOR}" = "remove" ]; then
     if [ $BUILD -eq 0 -a $ONLYCONF -eq 0 ]; then
-      $PACMAN $ARGLIST
+      pacaur $ARGLIST
     fi
 
     for pkg in ${args[@]}; do
@@ -491,18 +451,18 @@ Another instance of srcpac is already running.\n\
 
   if [ "${MAJOR}" = "query" ]; then
     if [ $BUILD -eq 1 ]; then
-      for pkg in `find /var/lib/srcpac/ -type f`; do
-        $PACMAN -Q $(basename $pkg)
+      for pkg in `find ~/.config/srcpac/ -type f`; do
+        pacaur -Q $(basename $pkg)
       done
     elif [ $GROUP -eq 1 ]; then
-      $PACMAN -Qg ${args[@]}
+      pacaur -Qg ${args[@]}
     else
       for pkg in ${args[@]}; do
         local valid=1
         if [ $INFO -eq 1 ]; then
-          $PACMAN -Qi $pkg && valid=0 | head -n -1
+          pacaur -Qi $pkg && valid=0 | head -n -1
         else
-          echo -n $($PACMAN -Q $pkg) && valid=0
+          echo -n $(pacaur -Q $pkg) && valid=0
         fi
 
         if [ $valid -eq 0 ]; then
@@ -516,7 +476,7 @@ Another instance of srcpac is already running.\n\
               printf "$(gettext "No")\n"
             fi
             printf "$(gettext "Patchfile      : ")"
-            if [ -f /etc/srcpac.d/$pkg ]; then
+            if [ -f ~/.config/srcpac.d/$pkg ]; then
               printf "$(gettext "Yes")\n"
             else
               printf "$(gettext "No")\n"
@@ -542,9 +502,9 @@ Another instance of srcpac is already running.\n\
 
         if [ $IGNORE -eq 1 ]; then
           local ignorestr=$(echo $IGNOREPKG | tr "," "|")
-          local output=$($PACMAN -Qqu --noconfirm | grep -Ev ${ignorestr})
+          local output=$(pacaur -Qqu --noconfirm | grep -Ev ${ignorestr})
         else
-          local output=$($PACMAN -Qqu --noconfirm)
+          local output=$(pacaur -Qqu --noconfirm)
         fi
 
         # regular packages, these have not been built with srcpac
@@ -568,7 +528,7 @@ Another instance of srcpac is already running.\n\
         [ $NOCONFIRM -eq 1 ] && PACARGS="${PACARGS} --noconfirm"
 
         if [ -n "${regpkg[*]}" ]; then
-          $PACMAN $PACARGS ${regpkg[@]}
+          pacaur $PACARGS ${regpkg[@]}
         fi
 
         for pkg in $packages; do
@@ -576,7 +536,7 @@ Another instance of srcpac is already running.\n\
         done
       else
         [ $REFRESH -eq 1 ] && refresh
-        $PACMAN $ARGLIST
+        pacaur $ARGLIST
         exit 0
       fi
     else
@@ -585,16 +545,16 @@ Another instance of srcpac is already running.\n\
       if [ $SYSUPGRADE -eq 1 ]; then
         if [ $IGNORE -eq 1 ]; then
           local ignorestr=$(echo $IGNOREPKG | tr "," "|")
-          local packages=$($PACMAN -Qqu --noconfirm | grep -Ev ${ignorestr})
+          local packages=$(pacaur -Qqu --noconfirm | grep -Ev ${ignorestr})
         else
-          local packages=$($PACMAN -Qqu --noconfirm)
+          local packages=$(pacaur -Qqu --noconfirm)
         fi
       else
         local packages="${args[@]}"
       fi
 
       if [ $GROUP -eq 1 ]; then
-        for pkg in $($PACMAN -Sqg $packages); do
+        for pkg in $(pacaur -Sqg $packages); do
           get_candidates $pkg 1
         done
       else
@@ -618,9 +578,10 @@ Another instance of srcpac is already running.\n\
       fi
     fi
 
+	# packages will be built by srcpac
     if [ -n "${candidates[*]}" ]; then
 
-      touch /run/srcpac.lock
+      touch ~/.config/srcpac.lock
 
       echo
       printf "$(gettext "Source Targets:") "
@@ -632,7 +593,7 @@ Another instance of srcpac is already running.\n\
         printf "$(gettext "Proceed? [Y/n]") "
         read
         if [ "${REPLY}" != "$(gettext "y")" -a "${REPLY}" != "$(gettext "Y")" -a "${REPLY}" != "" ]; then
-          rm /run/srcpac.lock &> /dev/null
+          rm ~/.config/srcpac.lock &> /dev/null
           exit 0
         fi
       fi
@@ -641,7 +602,7 @@ Another instance of srcpac is already running.\n\
         build_package "install" ${pkg}
       done
 
-      rm /run/srcpac.lock &> /dev/null
+      rm ~/.config/srcpac.lock &> /dev/null
     fi
 
     if [ -n "${broken}" ]; then
