nearly done

diff --git a/srcpac b/srcpac
--- a/srcpac
+++ b/srcpac
@@ -1,6 +1,28 @@
-#/bin/bash
+
+# 
+#   srcpac
+#  
+#   Copyright (c) 2004 by Jason Chu <jason@archlinux.org>
+#
+#   This program is free software; you can redistribute it and/or modify
+#   it under the terms of the GNU General Public License as published by
+#   the Free Software Foundation; either version 2 of the License, or
+#   (at your option) any later version.
+# 
+#   This program is distributed in the hope that it will be useful,
+#   but WITHOUT ANY WARRANTY; without even the implied warranty of
+#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#   GNU General Public License for more details.
+#  
+#   You should have received a copy of the GNU General Public License
+#   along with this program; if not, write to the Free Software
+#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
+#   USA.
+#
 
 ver=0.1
+
+[ -f /etc/abs/abs.conf ] && source /etc/abs/abs.conf
 
 usage()
 {
@@ -27,6 +49,12 @@ version()
 
 	exit 0
 }
+
+strip_url() {
+	echo $1 | sed 's|^.*://.*/||g'
+}
+
+
 
 # Options
 MAJOR=""
@@ -163,6 +191,11 @@ if [ "$MAJOR" = "query" ]; then
 	if [ $INFO -eq 1 -a -d /var/lib/srcpac ]; then
 		for arg in ${args[@]}; do
 			pacman $ARGSANS $arg | head -n -1
+
+			if [ $? -ne 0 ]; then
+				exit $?
+			fi
+
 			echo -n "Source         : "
 			if [ -L /var/lib/srcpac/$arg ]; then
 				echo "Yes"
@@ -181,5 +214,108 @@ if [ "$MAJOR" = "sync" ]; then
 		pacman $ARGLIST
 	else
 		# Insert magic here
+
+		if [ "$ABSROOT" = "" ]; then
+			echo "Error: The ABSROOT environment variable is not defined."
+
+			exit 1
+		fi
+
+		if [ $REFRESH -eq 1 ]; then
+			abs
+			pacman -Sy
+
+			if [ "${args[*]}" = "" ]; then
+				exit 0
+			fi
+		fi
+
+		if [ $DOWNLOAD -eq 1 ]; then
+			for i in ${args[@]}; do
+				candidates=`find $ABSROOT -type d -name $i`
+				if [ "$candidates" = "" ]; then
+					echo "Error: Could not find \"$i\" under $ABSROOT"
+
+					exit 1
+				fi
+				success=0
+				for pkgdir in $candidates; do
+					if [ -f $pkgdir/PKGBUILD ]; then
+						cd $pkgdir
+						makepkg -cfw /var/cache/pacman/pkg
+						if [ $? -eq 0 ]; then
+							success=1
+							break
+						fi
+					fi
+				done
+				if [ $success -eq 0 ]; then
+					echo "Error: Failed to build \"$i\""
+
+					exit 1
+				fi
+			done
+
+			exit 0
+		fi
+
+		if [ $SYSUPGRADE -eq 1 ]; then
+			true
+		else
+			# TODO: Needs support for "x is up to date.  Upgrade anyway?"
+			output=`yes "" | pacman -Sp ${args[*]}`
+
+			if [ $? -ne 0 ]; then
+				exit $?
+			fi
+
+			declare -a packages
+			for i in $output; do
+				if [ `echo $i | grep ^\\\\\\(ftp\\\\\\|http\\\\\\)` ]; then
+					i=${i%.pkg.tar.gz}
+					packages[${#packages[@]}]=`strip_url $i`
+				fi
+			done
+		fi
+
+		echo
+		echo "Source Targets: " ${packages[*]}
+		echo
+		echo -n "Proceed with upgrade? [Y/n] "
+		read
+		if [ "$REPLY" != "y" -a "$REPLY" != "Y" ]; then
+			exit 0
+		fi
+
+		if [ $ROOT -eq 0 ]; then
+			for i in ${packages[@]}; do
+				candidates=`find $ABSROOT -type d -name $i`
+				if [ "$candidates" = "" ]; then
+					echo "Error: Could not find \"$i\" under $ABSROOT"
+
+					exit 1
+				fi
+				success=0
+				for pkgdir in $candidates; do
+					if [ -f $pkgdir/PKGBUILD ]; then
+						cd $pkgdir
+						makepkg -icfw /var/cache/pacman/pkg
+						if [ $? -eq 0 ]; then
+							success=1
+							break
+						fi
+					fi
+				done
+				if [ $success -eq 0 ]; then
+					echo "Error: Failed to build \"$i\""
+
+					exit 1
+				fi
+			done
+
+			exit 0
+		else
+			echo "This feature isn't done yet"
+		fi
 	fi
 fi
