added -o option... should be in the -o release

diff --git a/srcpac b/srcpac
--- a/srcpac
+++ b/srcpac
@@ -56,6 +56,18 @@ strip_url()
 	echo $1 | sed 's|^.*://.*/||g'
 }
 
+do_confs()
+{
+	eval num_conf=\$\{\#conf_$1[@]\}
+	if [ $num_conf -gt 0 ]; then
+		sedvar=""
+		eval "for (( j = 0 ; j < $num_conf ; j++ )); do
+			sedvar=\"\${sedvar}s\${conf_$i[\$j]};\"
+		done"
+		eval sed -i \"$sedvar\" $2/PKGBUILD
+	fi
+}
+
 build_packages()
 {
 	while [ $# -ne 0 ]; do
@@ -70,14 +82,7 @@ build_packages()
 		for pkgdir in $candidates; do
 			if [ -f $pkgdir/PKGBUILD ]; then
 				# Look for config options and apply them
-				eval num_conf=\$\{\#conf_$i[@]\}
-				if [ $num_conf -gt 0 ]; then
-					sedvar=""
-					eval "for (( j = 0 ; j < $num_conf ; j++ )); do
-						sedvar=\"\${sedvar}s\${conf_$i[\$j]};\"
-					done"
-					eval sed -i \'$sedvar\' $pkgdir/PKGBUILD
-				fi
+				do_confs $i $pkgdir
 
 				cd $pkgdir
 				makepkg -cbrfw /var/cache/pacman/pkg
@@ -112,15 +117,7 @@ build_and_install_packages()
 		for pkgdir in $candidates; do
 			if [ -f $pkgdir/PKGBUILD ]; then
 				# Look for config options and apply them
-				eval num_conf=\$\{\#conf_$i[@]\}
-				if [ $num_conf -gt 0 ]; then
-					sedvar=""
-					eval "for (( j = 0 ; j < $num_conf ; j++ )); do
-						sedvar=\"\${sedvar}s\${conf_$i[\$j]};\"
-					done"
-#					eval echo sed -i \'$sedvar\' $pkgdir/PKGBUILD
-					eval sed -i \'$sedvar\' $pkgdir/PKGBUILD
-				fi
+				do_confs $i $pkgdir
 
 				cd $pkgdir
 				makepkg -ibrcfw /var/cache/pacman/pkg
@@ -157,6 +154,7 @@ BUILD=0
 REFRESH=0
 SYSUPGRADE=0
 DOWNLOAD=0
+ONLYCONF=0
 
 ARGLIST=$@
 ARGSANS=""
@@ -228,6 +226,10 @@ while [ "$#" -ne "0" ]; do
 			DOWNLOAD=1
 			ARGSANS="$ARGSANS $1"
 			;;
+		--onlyconf)
+			ONLYCONF=1
+			ARGSANS="$ARGSANS $1"
+			;;
 		--*)
 			usage
 			exit 1
@@ -237,7 +239,7 @@ while [ "$#" -ne "0" ]; do
 			if [ `echo $1 | grep r` ]; then
 				OPTIONAL=$2
 			fi
-			while getopts "VARUFQSidfbyur:w" opt $1 $OPTIONAL; do
+			while getopts "VARUFQSidfbyur:wo" opt $1 $OPTIONAL; do
 				case $opt in
 					V) version ;;
 					A) MAJOR="add" ;;
@@ -257,6 +259,7 @@ while [ "$#" -ne "0" ]; do
 					y) REFRESH=1 ;;
 					u) SYSUPGRADE=1 ;;
 					w) DOWNLOAD=1 ;;
+					o) ONLYCONF=1 ;;
 				esac
 			done
 			;;
@@ -316,7 +319,7 @@ if [ "$MAJOR" = "query" ]; then
 fi
 
 if [ "$MAJOR" = "sync" ]; then
-	if [ $BUILD -eq 0 ]; then
+	if [ $BUILD -eq 0 -a $ONLYCONF -ne 1 ]; then
 		if [ $SYSUPGRADE -eq 1 -a -d /var/lib/srcpac ]; then
 			# TODO: Needs support for "x is up to date.  Upgrade anyway?"
 			if [ $REFRESH -eq 1 ]; then
@@ -414,6 +417,34 @@ if [ "$MAJOR" = "sync" ]; then
 		done
 
 		if [ ${#packages[@]} -eq 0 ]; then
+			exit 0
+		fi
+
+		if [ $ONLYCONF -eq 1 ]; then
+			for i in ${packages[@]}; do
+				i=${i%-*-*}
+				candidates=`find $ABSROOT -type d -name $i`
+				if [ "$candidates" = "" ]; then
+					echo "Error: Could not find \"$i\" under $ABSROOT"
+
+					exit 1
+				fi
+				success=0
+				for pkgdir in $candidates; do
+					if [ -f $pkgdir/PKGBUILD ]; then
+						# Look for config options and apply them
+						do_confs $i $pkgdir
+						less $pkgdir/PKGBUILD
+						success=1
+						break
+					fi
+				done
+				if [ $success -eq 0 ]; then
+					echo "Error: Failed to find \"$i\""
+
+					exit 1
+				fi
+			done
 			exit 0
 		fi
 
